// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBB0RvBaSyWGK0XpMlc2W-DClRE8Fc-0ys',
    appId: '1:586889472832:web:8ff51b08b1bb148c7e28a5',
    messagingSenderId: '586889472832',
    projectId: 'koramapp-52bf8',
    authDomain: 'koramapp-52bf8.firebaseapp.com',
    storageBucket: 'koramapp-52bf8.appspot.com',
    measurementId: 'G-JSSWTWPK0M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9TNzd3RehFQoMBvmNO9b9pV4hDa6DkHg',
    appId: '1:586889472832:android:a3cfa9fea86804647e28a5',
    messagingSenderId: '586889472832',
    projectId: 'koramapp-52bf8',
    storageBucket: 'koramapp-52bf8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDk-Ksej-hMboJ1swQUjHcoTu0zF9ydFJU',
    appId: '1:586889472832:ios:96e4b001f0bce3a27e28a5',
    messagingSenderId: '586889472832',
    projectId: 'koramapp-52bf8',
    storageBucket: 'koramapp-52bf8.appspot.com',
    iosBundleId: 'com.koram.app.koramnew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDk-Ksej-hMboJ1swQUjHcoTu0zF9ydFJU',
    appId: '1:586889472832:ios:96e4b001f0bce3a27e28a5',
    messagingSenderId: '586889472832',
    projectId: 'koramapp-52bf8',
    storageBucket: 'koramapp-52bf8.appspot.com',
    iosBundleId: 'com.koram.app.koramnew',
  );
}
